### ISSUE TITLE
Broken links SEO

### ISSUE THREAD

**Issue by ghoshbishakh** [swrdfish/jk#21]
Link gulo # dea kichu dea dite hobe

![image](https://user-images.githubusercontent.com/5156787/27252808-d9a1c76a-5384-11e7-92f7-248463ec2c8c.png)

**Comment by ghoshbishakh** [comment]
@swrdfish just change kore dilei hobe to?

**Comment by swrdfish** [comment]
ei link ta era pelo kothai?

**Comment by swrdfish** [comment]
oha eta just # kore de.
